### ISSUE TITLE
Only the Person type is displayed in the reconciliation choices

### ISSUE THREAD

**Issue by JBPressac** [codeforkjeff/refine_viaf#4]
Hello,
Only the Person type is displayed in the reconciliation choices (see screen capture). Problem reproduced with a local version of refine_viaf-1.4.jar + Java Version 8 Update 91 and on http://refine.codefork.com/reconcile/viafproxy/BNF.

![2016-06-17 08_58_22-prelib_personne140616 csv _ refine codefork com with accents - openrefine](https://cloud.githubusercontent.com/assets/6371750/16143465/3a806f7e-346d-11e6-8497-fd464c3ebd55.png)

**Comment by codeforkjeff** [comment]
When you select a reconciliation service in OpenRefine, it will try to reconcile the first 10 rows, and then show you a list of entity types based on those 10 "test" cases. It only shows you Person because your names look like Persons and not other types. This is correct.

If you create a new project with different data that could be Geographic names or names of Works, those types should appear.

**Comment by JBPressac** [comment]
Thank you !
